server:
  port: 9000

eureka:
  server:
#  https://github.com/spring-cloud/spring-cloud-netflix/issues/1844
    enable-self-preservation: false
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  security:
    user:
      name: system
      password: system
      roles: SYSTEM